/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-error': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed': '#0b1c30',
        outline: '#76777d',
        'on-surface-variant': '#45464d',
        'outline-variant': '#c6c6cd',
        'on-secondary-fixed-variant': '#003ea8',
        'inverse-on-surface': '#eff1f3',
        tertiary: '#000000',
        'on-surface': '#191c1e',
        'surface-dim': '#d8dadc',
        'surface-container-low': '#f2f4f6',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-primary-container': '#7c839b',
        'on-secondary-fixed': '#00174b',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f7f9fb',
        'primary-fixed-dim': '#bec6e0',
        'primary-fixed': '#dae2fd',
        'on-tertiary-container': '#75859d',
        'on-error-container': '#93000a',
        'secondary-container': '#316bf3',
        'surface-container': '#eceef0',
        'primary-container': '#131b2e',
        'surface-variant': '#e0e3e5',
        secondary: '#0051d5',
        background: '#f7f9fb',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed': '#d3e4fe',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-tint': '#565e74',
        'inverse-primary': '#bec6e0',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#3f465c',
        'on-tertiary-fixed-variant': '#38485d',
        'tertiary-container': '#0b1c30',
        'secondary-fixed': '#dbe1ff',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
        'on-secondary-container': '#fefcff',
        'on-primary-fixed': '#131b2e',
        'on-background': '#191c1e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      spacing: {
        'max-width': '1280px',
        'margin-desktop': '2.5rem',
        lg: '1.5rem',
        xs: '0.25rem',
        sm: '0.5rem',
        'margin-mobile': '1rem',
        base: '4px',
        gutter: '1.5rem',
        xl: '2rem',
        md: '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
